/* 
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISegmentEffortsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// List Segment Efforts
        /// </summary>
        /// <remarks>
        /// Returns a set of the authenticated athlete&#39;s segment efforts for a given segment.  Requires subscription.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="segmentId">The identifier of the segment.</param>
        /// <param name="startDateLocal">ISO 8601 formatted date time. (optional)</param>
        /// <param name="endDateLocal">ISO 8601 formatted date time. (optional)</param>
        /// <param name="perPage">Number of items per page. Defaults to 30. (optional, default to 30)</param>
        /// <returns>List&lt;DetailedSegmentEffort&gt;</returns>
        List<DetailedSegmentEffort> GetEffortsBySegmentId (int? segmentId, DateTime? startDateLocal = null, DateTime? endDateLocal = null, int? perPage = null);

        /// <summary>
        /// List Segment Efforts
        /// </summary>
        /// <remarks>
        /// Returns a set of the authenticated athlete&#39;s segment efforts for a given segment.  Requires subscription.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="segmentId">The identifier of the segment.</param>
        /// <param name="startDateLocal">ISO 8601 formatted date time. (optional)</param>
        /// <param name="endDateLocal">ISO 8601 formatted date time. (optional)</param>
        /// <param name="perPage">Number of items per page. Defaults to 30. (optional, default to 30)</param>
        /// <returns>ApiResponse of List&lt;DetailedSegmentEffort&gt;</returns>
        ApiResponse<List<DetailedSegmentEffort>> GetEffortsBySegmentIdWithHttpInfo (int? segmentId, DateTime? startDateLocal = null, DateTime? endDateLocal = null, int? perPage = null);
        /// <summary>
        /// Get Segment Effort
        /// </summary>
        /// <remarks>
        /// Returns a segment effort from an activity that is owned by the authenticated athlete. Requires subscription.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The identifier of the segment effort.</param>
        /// <returns>DetailedSegmentEffort</returns>
        DetailedSegmentEffort GetSegmentEffortById (long? id);

        /// <summary>
        /// Get Segment Effort
        /// </summary>
        /// <remarks>
        /// Returns a segment effort from an activity that is owned by the authenticated athlete. Requires subscription.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The identifier of the segment effort.</param>
        /// <returns>ApiResponse of DetailedSegmentEffort</returns>
        ApiResponse<DetailedSegmentEffort> GetSegmentEffortByIdWithHttpInfo (long? id);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// List Segment Efforts
        /// </summary>
        /// <remarks>
        /// Returns a set of the authenticated athlete&#39;s segment efforts for a given segment.  Requires subscription.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="segmentId">The identifier of the segment.</param>
        /// <param name="startDateLocal">ISO 8601 formatted date time. (optional)</param>
        /// <param name="endDateLocal">ISO 8601 formatted date time. (optional)</param>
        /// <param name="perPage">Number of items per page. Defaults to 30. (optional, default to 30)</param>
        /// <returns>Task of List&lt;DetailedSegmentEffort&gt;</returns>
        System.Threading.Tasks.Task<List<DetailedSegmentEffort>> GetEffortsBySegmentIdAsync (int? segmentId, DateTime? startDateLocal = null, DateTime? endDateLocal = null, int? perPage = null);

        /// <summary>
        /// List Segment Efforts
        /// </summary>
        /// <remarks>
        /// Returns a set of the authenticated athlete&#39;s segment efforts for a given segment.  Requires subscription.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="segmentId">The identifier of the segment.</param>
        /// <param name="startDateLocal">ISO 8601 formatted date time. (optional)</param>
        /// <param name="endDateLocal">ISO 8601 formatted date time. (optional)</param>
        /// <param name="perPage">Number of items per page. Defaults to 30. (optional, default to 30)</param>
        /// <returns>Task of ApiResponse (List&lt;DetailedSegmentEffort&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<DetailedSegmentEffort>>> GetEffortsBySegmentIdAsyncWithHttpInfo (int? segmentId, DateTime? startDateLocal = null, DateTime? endDateLocal = null, int? perPage = null);
        /// <summary>
        /// Get Segment Effort
        /// </summary>
        /// <remarks>
        /// Returns a segment effort from an activity that is owned by the authenticated athlete. Requires subscription.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The identifier of the segment effort.</param>
        /// <returns>Task of DetailedSegmentEffort</returns>
        System.Threading.Tasks.Task<DetailedSegmentEffort> GetSegmentEffortByIdAsync (long? id);

        /// <summary>
        /// Get Segment Effort
        /// </summary>
        /// <remarks>
        /// Returns a segment effort from an activity that is owned by the authenticated athlete. Requires subscription.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The identifier of the segment effort.</param>
        /// <returns>Task of ApiResponse (DetailedSegmentEffort)</returns>
        System.Threading.Tasks.Task<ApiResponse<DetailedSegmentEffort>> GetSegmentEffortByIdAsyncWithHttpInfo (long? id);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SegmentEffortsApi : ISegmentEffortsApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SegmentEffortsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SegmentEffortsApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SegmentEffortsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SegmentEffortsApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// List Segment Efforts Returns a set of the authenticated athlete&#39;s segment efforts for a given segment.  Requires subscription.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="segmentId">The identifier of the segment.</param>
        /// <param name="startDateLocal">ISO 8601 formatted date time. (optional)</param>
        /// <param name="endDateLocal">ISO 8601 formatted date time. (optional)</param>
        /// <param name="perPage">Number of items per page. Defaults to 30. (optional, default to 30)</param>
        /// <returns>List&lt;DetailedSegmentEffort&gt;</returns>
        public List<DetailedSegmentEffort> GetEffortsBySegmentId (int? segmentId, DateTime? startDateLocal = null, DateTime? endDateLocal = null, int? perPage = null)
        {
             ApiResponse<List<DetailedSegmentEffort>> localVarResponse = GetEffortsBySegmentIdWithHttpInfo(segmentId, startDateLocal, endDateLocal, perPage);
             return localVarResponse.Data;
        }

        /// <summary>
        /// List Segment Efforts Returns a set of the authenticated athlete&#39;s segment efforts for a given segment.  Requires subscription.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="segmentId">The identifier of the segment.</param>
        /// <param name="startDateLocal">ISO 8601 formatted date time. (optional)</param>
        /// <param name="endDateLocal">ISO 8601 formatted date time. (optional)</param>
        /// <param name="perPage">Number of items per page. Defaults to 30. (optional, default to 30)</param>
        /// <returns>ApiResponse of List&lt;DetailedSegmentEffort&gt;</returns>
        public ApiResponse< List<DetailedSegmentEffort> > GetEffortsBySegmentIdWithHttpInfo (int? segmentId, DateTime? startDateLocal = null, DateTime? endDateLocal = null, int? perPage = null)
        {
            // verify the required parameter 'segmentId' is set
            if (segmentId == null)
                throw new ApiException(400, "Missing required parameter 'segmentId' when calling SegmentEffortsApi->GetEffortsBySegmentId");

            var localVarPath = "/segment_efforts";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (segmentId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "segment_id", segmentId)); // query parameter
            if (startDateLocal != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "start_date_local", startDateLocal)); // query parameter
            if (endDateLocal != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "end_date_local", endDateLocal)); // query parameter
            if (perPage != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "per_page", perPage)); // query parameter

            // authentication (strava_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEffortsBySegmentId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<DetailedSegmentEffort>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<DetailedSegmentEffort>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<DetailedSegmentEffort>)));
        }

        /// <summary>
        /// List Segment Efforts Returns a set of the authenticated athlete&#39;s segment efforts for a given segment.  Requires subscription.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="segmentId">The identifier of the segment.</param>
        /// <param name="startDateLocal">ISO 8601 formatted date time. (optional)</param>
        /// <param name="endDateLocal">ISO 8601 formatted date time. (optional)</param>
        /// <param name="perPage">Number of items per page. Defaults to 30. (optional, default to 30)</param>
        /// <returns>Task of List&lt;DetailedSegmentEffort&gt;</returns>
        public async System.Threading.Tasks.Task<List<DetailedSegmentEffort>> GetEffortsBySegmentIdAsync (int? segmentId, DateTime? startDateLocal = null, DateTime? endDateLocal = null, int? perPage = null)
        {
             ApiResponse<List<DetailedSegmentEffort>> localVarResponse = await GetEffortsBySegmentIdAsyncWithHttpInfo(segmentId, startDateLocal, endDateLocal, perPage);
             return localVarResponse.Data;

        }

        /// <summary>
        /// List Segment Efforts Returns a set of the authenticated athlete&#39;s segment efforts for a given segment.  Requires subscription.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="segmentId">The identifier of the segment.</param>
        /// <param name="startDateLocal">ISO 8601 formatted date time. (optional)</param>
        /// <param name="endDateLocal">ISO 8601 formatted date time. (optional)</param>
        /// <param name="perPage">Number of items per page. Defaults to 30. (optional, default to 30)</param>
        /// <returns>Task of ApiResponse (List&lt;DetailedSegmentEffort&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<DetailedSegmentEffort>>> GetEffortsBySegmentIdAsyncWithHttpInfo (int? segmentId, DateTime? startDateLocal = null, DateTime? endDateLocal = null, int? perPage = null)
        {
            // verify the required parameter 'segmentId' is set
            if (segmentId == null)
                throw new ApiException(400, "Missing required parameter 'segmentId' when calling SegmentEffortsApi->GetEffortsBySegmentId");

            var localVarPath = "/segment_efforts";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (segmentId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "segment_id", segmentId)); // query parameter
            if (startDateLocal != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "start_date_local", startDateLocal)); // query parameter
            if (endDateLocal != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "end_date_local", endDateLocal)); // query parameter
            if (perPage != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "per_page", perPage)); // query parameter

            // authentication (strava_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEffortsBySegmentId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<DetailedSegmentEffort>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<DetailedSegmentEffort>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<DetailedSegmentEffort>)));
        }

        /// <summary>
        /// Get Segment Effort Returns a segment effort from an activity that is owned by the authenticated athlete. Requires subscription.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The identifier of the segment effort.</param>
        /// <returns>DetailedSegmentEffort</returns>
        public DetailedSegmentEffort GetSegmentEffortById (long? id)
        {
             ApiResponse<DetailedSegmentEffort> localVarResponse = GetSegmentEffortByIdWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Segment Effort Returns a segment effort from an activity that is owned by the authenticated athlete. Requires subscription.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The identifier of the segment effort.</param>
        /// <returns>ApiResponse of DetailedSegmentEffort</returns>
        public ApiResponse< DetailedSegmentEffort > GetSegmentEffortByIdWithHttpInfo (long? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling SegmentEffortsApi->GetSegmentEffortById");

            var localVarPath = "/segment_efforts/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (strava_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSegmentEffortById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DetailedSegmentEffort>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DetailedSegmentEffort) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DetailedSegmentEffort)));
        }

        /// <summary>
        /// Get Segment Effort Returns a segment effort from an activity that is owned by the authenticated athlete. Requires subscription.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The identifier of the segment effort.</param>
        /// <returns>Task of DetailedSegmentEffort</returns>
        public async System.Threading.Tasks.Task<DetailedSegmentEffort> GetSegmentEffortByIdAsync (long? id)
        {
             ApiResponse<DetailedSegmentEffort> localVarResponse = await GetSegmentEffortByIdAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Segment Effort Returns a segment effort from an activity that is owned by the authenticated athlete. Requires subscription.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The identifier of the segment effort.</param>
        /// <returns>Task of ApiResponse (DetailedSegmentEffort)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DetailedSegmentEffort>> GetSegmentEffortByIdAsyncWithHttpInfo (long? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling SegmentEffortsApi->GetSegmentEffortById");

            var localVarPath = "/segment_efforts/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (strava_oauth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetSegmentEffortById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DetailedSegmentEffort>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DetailedSegmentEffort) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DetailedSegmentEffort)));
        }

    }
}
