name: Build & Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Build & Publish
        run: dotnet publish -c Release -o deploy
      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@0.9.0
        with:
          local: /home/runner/work/strava-discord-bot/strava-discord-bot/deploy/
          remote: /root/bot/src/ 
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.REMOTE_SSH_KEY }}
      - name: Restart bot
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo systemctl stop ${{ secrets.REMOTE_SERVICE_NAME }} && sudo systemctl start ${{ secrets.REMOTE_SERVICE_NAME }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.REMOTE_SSH_KEY }}
