name: Build & Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Build & Publish
        run: dotnet publish -c Release -o deploy

      - name:  Copy via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: /home/runner/work/strava-discord-bot/strava-discord-bot/deploy/
          target: /root/bot/src/ 

      - name: Restart bot
        uses: appleboy/ssh-action@v1.0.3
        with:
          script: sudo systemctl stop ${{ secrets.REMOTE_SERVICE_NAME }} && sudo systemctl start ${{ secrets.REMOTE_SERVICE_NAME }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
